package com.github.pedroluis02.fixedpdfgen.service

import com.github.pedroluis02.fixedpdfgen.writer.FixedPdfTextGenerator
import com.github.pedroluis02.fixedpdfgen.writer.UnitMeasure

class PdfGeneratorSampleService : FixedPdfTextGenerator(21f, 29.7f, UnitMeasure.CENTIMETERS) {

    override fun onAddElements() {
        addFixedText("Fixed PDF Text", 5f, 2f, 14f)
        addFixedText("PDF generated by OpenPDF Library", 5f, 3f)
    }
}
