package com.github.pedroluis02.fixedpdfgen

import com.github.pedroluis02.fixedpdfgen.writer.FixedPdfTextGenerator
import com.github.pedroluis02.fixedpdfgen.writer.UnitMeasure
import java.io.File
import kotlin.test.Test
import kotlin.test.assertTrue

class TitlePdfTextGeneratorTest {

    @Test
    fun shouldGeneratePdf() {
        val generator = TitlePdfGenerator()

        val output = "title-file.pdf"
        generator.generateFile(output)

        val file = File(output)
        assertTrue(file.exists())

        assertTrue(file.delete())
    }
}

private class TitlePdfGenerator : FixedPdfTextGenerator(21f, 29.7f, UnitMeasure.CENTIMETERS) {

    override fun onAddElements() {
        addFixedText("Fixed PDF Text", 5f, 2f, 14f)
        addFixedText("PDF generated by OpenPDF Library", 5f, 3f)
    }
}

